Googlemap page
AndresEstebanGonzalez/carsaas-kitchen-recreate pull request #2
Opened 2021-02-18 22:29 UTC by AndresEstebanGonzalez

Second page (Googlemaps background) is near complete. Need to go back and see the font sizes. Need to put navbar to fixed and turn black.

2021-02-19 00:39 UTC, nathan-hyan requested changes
Some comments

2021-02-19 00:39 UTC, nathan-hyan commented on styles/_googlemaps.scss
> +  padding: 0 1rem 0 0;
This case is better to use `padding-right: 1rem`

2021-02-19 00:39 UTC, nathan-hyan commented on styles/_googlemaps.scss
> +    padding: 0 1rem 0 0;
Same here

2021-02-19 00:39 UTC, nathan-hyan commented on styles/_googlemaps.scss
> +  .right--sector-text h3 {
not sassy enough

```
.right--sector-text {
...
h3 {
...stuff
}
}
```

2021-02-19 00:39 UTC, nathan-hyan commented on styles/_googlemaps.scss
> +  .right--sector-text p {
same as above

2021-02-19 00:39 UTC, nathan-hyan commented on styles/styles.scss
> +@import url("https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap");
Google fonts lets you import various fontweights into one link

2021-02-24 15:51 UTC, AndresEstebanGonzalez reviewed
Comments review and corrected.

2021-02-24 15:51 UTC, nathan-hyan requested changes
More comments

2021-02-24 15:51 UTC, nathan-hyan commented on styles/_googlemaps.scss
> +    border: 0 none;
`border: none;` will do the trick just fine

2021-02-24 15:51 UTC, nathan-hyan commented on styles/_googlemaps.scss
> +      background-color: rgba(0, 0, 0, 0.8);
use variables for colors

2021-02-24 15:51 UTC, nathan-hyan commented on styles/_googlemaps.scss
> +        color: #dddddd;
same here

2021-02-24 15:51 UTC, nathan-hyan commented on styles/_googlemaps.scss
> +          color: #6ab04c;
same here

2021-02-24 15:51 UTC, nathan-hyan commented on styles/_googlemaps.scss
> +      color: #6ab04c;
same here

2021-02-24 15:51 UTC, nathan-hyan commented on styles/_navbar.scss
> +      color: white;
use variables with colors

2021-02-24 16:55 UTC, nathan-hyan requested changes
Last comments

2021-02-24 16:55 UTC, nathan-hyan commented on styles/_colors.scss
> +$color-white: white;
use only hex values

2021-02-24 16:55 UTC, nathan-hyan commented on styles/_colors.scss
> +$color-black: #000000cc;
Hex values can only have either 3 or 6 numbers

2021-02-24 16:55 UTC, nathan-hyan commented on styles/_colors.scss
> +$color-black-transparent: #000000ea;
in this case AND ONLY WITH TRANSPARENCY you can use rgba()

`rgba($black, 0.5)`

2021-02-24 17:47 UTC, nathan-hyan approved these changes
🥇

2021-02-24 17:58 UTC, merged